[[check]]
type = "Exclude"
id = "STAN-0001"
scope = "all"

[[check]]
type = "Exclude"
id = "STAN-0101"
scope = "all"

[[check]]
type = "Exclude"
id = "STAN-0103"
scope = "all"

[[check]]
type = "Exclude"
id = "STAN-0105"
scope = "all"
